micronaut:
    application:
        name: micronaut-vuejs
                
    server:
        port: 8090

# mongodb:
#     uri: mongodb://localhost:27017/test

grails:
    mongodb:
        databaseName: micronaut

mongodb:
    uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

# datasources:
#     default:
#         url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#         username: sa
#         password: ""
#         driverClassName: org.h2.Driver

